### ISSUE TITLE
MyPage 만들기(WEEK2-4일차)

### ISSUE THREAD

**Issue by wjdals83** [semi-project-team/PSMC#89]
# ☘️#89. MyPage 만들기

### 업무구분
>기능개발

### 기능구분
>조회, 수정

- [x] 1. MyPage 에서 프로필 사진 띄우기
- [x] 2. MyPage 에서 내 정보 조회하기(id, phoneNumber, email, 연구실 번호, 전공분야, 의료진 코드, 사원 코드, 직급
- [x] 3. 변경하기버튼 클릭 시 id, phoneNumber, email, 연구실 번호 변경하기 

##### 부가설명
>피그마를 참고하여 디자인, 사진 등록 시 사진 주소를 저장할 DB 필요

**Comment by comaserious** [comment]
완료
